"""add subscription fields

Revision ID: 000759ab64bd
Revises: e2d785efb261
Create Date: 2026-06-11 13:28:54.719406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000759ab64bd'
down_revision = 'e2d785efb261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mercado_pago_subscription_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('next_billing_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('next_billing_at')
        batch_op.drop_column('mercado_pago_subscription_id')

    # ### end Alembic commands ###
