"""changing name columns

Revision ID: 19fc6c9d481e
Revises: c11b7fcdb21f
Create Date: 2026-05-28 17:21:27.207052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fc6c9d481e'
down_revision = 'c11b7fcdb21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=False))
        batch_op.drop_column('customer_name')
        batch_op.drop_column('customer_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
