"""add worker_schedule

Revision ID: 1f296bca5471
Revises: 1f95f810b21b
Create Date: 2026-05-28 12:11:09.461820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f296bca5471'
down_revision = '1f95f810b21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'weekday', name='uq_worker_schedule_weekday')
    )
    with op.batch_alter_table('worker_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_schedules_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_schedules_worker_id'), ['worker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_schedules_worker_id'))
        batch_op.drop_index(batch_op.f('ix_worker_schedules_company_id'))

    op.drop_table('worker_schedules')
    # ### end Alembic commands ###
