"""update user and company models

Revision ID: 308458b1a19a
Revises: cb552421ab61
Create Date: 2026-05-11 18:28:44.290443

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308458b1a19a'
down_revision = 'cb552421ab61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###

    with op.batch_alter_table('companies', schema=None) as batch_op:

        batch_op.add_column(
            sa.Column(
                'status',
                sa.String(length=30),
                nullable=False,
                server_default='pending_payment'
            )
        )

        batch_op.add_column(
            sa.Column(
                'plan',
                sa.String(length=30),
                nullable=False,
                server_default='basic'
            )
        )

        batch_op.add_column(
            sa.Column(
                'mercado_pago_payment_id',
                sa.String(length=120),
                nullable=True
            )
        )

        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###

    with op.batch_alter_table('companies', schema=None) as batch_op:

        batch_op.add_column(
            sa.Column(
                'active',
                sa.BOOLEAN(),
                autoincrement=False,
                nullable=False,
                server_default=sa.true()
            )
        )

        batch_op.drop_column('mercado_pago_payment_id')
        batch_op.drop_column('plan')
        batch_op.drop_column('status')

    # ### end Alembic commands ###