"""phone

Revision ID: 39bd87b37679
Revises: ebf8a0298126
Create Date: 2026-05-30 23:16:24.380763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bd87b37679'
down_revision = 'ebf8a0298126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.drop_column('customer_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
