"""add worker and company relationship

Revision ID: 40384a8c63f6
Revises: 4d4635ca3491
Create Date: 2026-05-26 20:58:52.402726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40384a8c63f6'
down_revision = '4d4635ca3491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('worker_id')

    # ### end Alembic commands ###
