"""products for admin

Revision ID: 4d4635ca3491
Revises: 2f010a26e2ac
Create Date: 2026-05-18 09:17:31.304616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4635ca3491'
down_revision = '2f010a26e2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('status')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('total_price')
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
