"""fixing sales record

Revision ID: 906f49faffa5
Revises: 19fc6c9d481e
Create Date: 2026-05-30 12:40:32.464751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '906f49faffa5'
down_revision = '19fc6c9d481e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('external_reference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('sold_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.alter_column('sold_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('external_reference')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
