"""removing constraint weekday worker_id

Revision ID: 9dfec7ff0bb9
Revises: a1e13a98b47c
Create Date: 2026-07-19 22:21:27.369734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfec7ff0bb9'
down_revision = 'a1e13a98b47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_worker_schedule_weekday'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_schedules', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_worker_schedule_weekday'), ['worker_id', 'weekday'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
