"""add company background and text colors

Revision ID: a1e13a98b47c
Revises: 000759ab64bd
Create Date: 2026-07-14 16:10:16.286765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e13a98b47c'
down_revision = '000759ab64bd'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'background_color',
                sa.String(length=7),
                nullable=False,
                server_default="#ffffff"
            )
        )

        batch_op.add_column(
            sa.Column(
                'text_color',
                sa.String(length=7),
                nullable=False,
                server_default="#000000"
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('text_color')
        batch_op.drop_column('background_color')

    # ### end Alembic commands ###
