"""deleting time_slot

Revision ID: c11b7fcdb21f
Revises: 1f296bca5471
Create Date: 2026-05-28 17:04:27.642986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c11b7fcdb21f'
down_revision = '1f296bca5471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "schedules_slot_id_fkey",
    "schedules",
    type_="foreignkey"
)
    op.drop_table('time_slots')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=30), nullable=False))
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        
        batch_op.create_index(batch_op.f('ix_schedules_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_worker_id'), ['worker_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('schedules_service_id_fkey'), type_='foreignkey')

        batch_op.drop_constraint(batch_op.f('schedules_worker_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')
        batch_op.drop_column('slot_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('schedules_worker_id_fkey'), 'workers', ['worker_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('schedules_slot_id_fkey'), 'time_slots', ['slot_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('schedules_service_id_fkey'), 'services', ['service_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_schedules_worker_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_start_time'))
        batch_op.drop_index(batch_op.f('ix_schedules_service_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_end_time'))
        batch_op.drop_index(batch_op.f('ix_schedules_company_id'))
        batch_op.create_unique_constraint(batch_op.f('schedules_slot_id_key'), ['slot_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    op.create_table('time_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('time_slots_company_id_fkey')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('time_slots_worker_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('time_slots_pkey'))
    )
    # ### end Alembic commands ###
