"""add customer fields

Revision ID: cc3bc5d56f89
Revises: 906f49faffa5
Create Date: 2026-05-30 22:58:00.109816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3bc5d56f89'
down_revision = '906f49faffa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
