"""fluxo de pagamento

Revision ID: e2d785efb261
Revises: 39bd87b37679
Create Date: 2026-05-31 12:35:05.524793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d785efb261'
down_revision = '39bd87b37679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercado_pago_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('mp_user_id', sa.BigInteger(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_user_id')
    )
    with op.batch_alter_table('mercado_pago_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mercado_pago_accounts_company_id'), ['company_id'], unique=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('companies_slug_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_companies_slug'), ['slug'], unique=True)

    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mercado_pago_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_column('payment_date')
        batch_op.drop_column('mercado_pago_status')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_slug'))
        batch_op.create_unique_constraint(batch_op.f('companies_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('mercado_pago_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mercado_pago_accounts_company_id'))

    op.drop_table('mercado_pago_accounts')
    # ### end Alembic commands ###
