"""add slot_interval to company

Revision ID: e862267a76bd
Revises: 9f6cbcdce00a
Create Date: 2026-08-01 10:05:22.894014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e862267a76bd'
down_revision = '9f6cbcdce00a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_interval', sa.Integer(), nullable=False, server_default='30'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('slot_interval')

    # ### end Alembic commands ###
