"""fixing customer fields

Revision ID: ebf8a0298126
Revises: cc3bc5d56f89
Create Date: 2026-05-30 23:05:19.166646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf8a0298126'
down_revision = 'cc3bc5d56f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=50), nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('customer_phone')

    # ### end Alembic commands ###
